### ISSUE TITLE
"Auto" state

### ISSUE THREAD

**Issue by pbb72** [AlfieJones/theme-toggles#18]
There should be an indicator for "auto" state also; this is when the theme follows the operating system settings. (For example, where the OS switches to dark mode during night and light mode during day.)

**Comment by AlfieJones** [comment]
I can't really add a third state to these toggles but what I would recommend doing in these scenarios is having the toggle trigger a dropdown with system. Scroll to the bottom of https://nextra.site/ to see an example of what I mean

**Comment by pbb72** [comment]
On my own site I actually implemented it as a toggle. Click on the sun, it turns into a moon, click again it turns into an "A", and again to turn back into a sun. Judging by my visitor logs it seems my visitors understand how it works.

**Comment by AlfieJones** [comment]
I'll add a section to the docs about options for an auto mode. I'll offer that up as one of the options
