### ISSUE TITLE
False claims about accessibility.

### ISSUE THREAD

**Issue by matuzo** [AlfieJones/theme-toggles#21]
Hi,

the sentence "Our goal is to ensure the toggles remain as accessible as possible. This includes proper screen reader support." on your about page suggests that the examples on your website are accessible. Unfortunately, that's not the case. All of the examples are either inaccessible with the keyboard, a screen reader or both.
Since it took me only 5 seconds to learn that, I have to assume that accessibility or, at least, accessibility testing in fact isn't your top priority. That's fine, given that this is a OS project you maintain in your spare time, but claiming that accessibility is "your goal" is misleading, especially for people who don't know how to test for accessibility and trust authors like you.

Please consider removing the misleading statements about accessibility until you or someone else fixes the issues. If you need help with that, feel free to get in touch.

Thank you.

**Comment by mikemai2awesome** [comment]
Second the above, and please do not encourage people to use `<div>` as buttons. If one chooses to use `<div>`, they would have to make sure proper aria attributes are applied, and custom JavaScript is written to replicate everything that a semantic button does. Your code snippets do not reflect this important piece of information.

**Comment by AlfieJones** [comment]
Thanks for the feedback 👍. I've gone ahead and removed the aforementioned statements. 

The issues described above are with the checkbox element, the button works better (although still has room for improvement).

I have created a new issue here to tack/give feedback on the new version https://github.com/AlfieJones/theme-toggles/issues/22
It has a link to a storybook where you can try out the new version of the toggles, any help on improving the accessibility is greatly welcomed

**Comment by AlfieJones** [comment]
> Second the above, and please do not encourage people to use `<div>` as buttons. If one chooses to use `<div>`, they would have to make sure proper aria attributes are applied, and custom JavaScript is written to replicate everything that a semantic button does. Your code snippets do not reflect this important piece of information.

I will be doing this in the new documentation
