### ISSUE TITLE
Div is not working.

### ISSUE THREAD

**Issue by foysalimran** [AlfieJones/theme-toggles#25]
<div class="theme-toggle" title="Toggle theme">
  <span class="theme-toggle-sr">Toggle theme</span>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
    width="1em"
    height="1em"
    fill="currentColor"
    stroke-linecap="round"
    class="theme-toggle__classic"
    viewBox="0 0 32 32"
  >
    <clipPath id="theme-toggle__classic__cutout">
      <path d="M0-5h30a1 1 0 0 0 9 13v24H0Z" />
    </clipPath>
    <g clip-path="url(#theme-toggle__classic__cutout)">
      <circle cx="16" cy="16" r="9.34" />
      <g stroke="currentColor" stroke-width="1.5">
        <path d="M16 5.5v-4" />
        <path d="M16 30.5v-4" />
        <path d="M1.5 16h4" />
        <path d="M26.5 16h4" />
        <path d="m23.4 8.6 2.8-2.8" />
        <path d="m5.7 26.3 2.9-2.9" />
        <path d="m5.8 5.8 2.8 2.8" />
        <path d="m23.4 23.4 2.9 2.9" />
      </g>
    </g>
  </svg>
</div>

I used this as markup and called it classic CSS. but seems it's not working it works if I use the checkbox wah. Do I need to do anything else?

**Comment by AlfieJones** [comment]
Could you share your code?

**Comment by AlfieJones** [comment]
I realised it's probably missing the theme-toggle--toggled. If you're using a div, you have to us js to toggle the classname "theme-toggle--toggled"

**Comment by foysalimran** [comment]
Ahh. Yes. Exactly. I solved it that way. Thank you so much for your reply. It should documented in the demo so anyone won't be confused. Thanks for this awesome product free of cost. I love it.

**Comment by AlfieJones** [comment]
Yeah In the next itteration of documentation I'll make it clear
