### ISSUE TITLE
System state

### ISSUE THREAD

**Issue by MoritzGlantz** [AlfieJones/theme-toggles#26]
Hey and thanks for these toggles! Great work!

When implementing I came across the issue, that if you only provide two states you’re locking the user in the decision he/she has made on the site. As pointed out in a blog article I [came across](https://tpiros.dev/blog/three-state-light-dark-theme-switch/), theme toggles need a third option which lets you go back to the state where the system settings decides which theme to take.

I was wondering if this could be considered in one of your animations. My idea would be to have either a cog icon or a state of the icon that shows both at once, like sun and moon at the same time.

If that is too far out for you, it’s fine with me 😊.

Have a nice day!

**Comment by davidbgk** [comment]
Looks to be a duplicate of #18 (I visited issues section for that feature too!)

**Comment by MoritzGlantz** [comment]
Yes, indeed. I did not identify the other issue to deal with the same topic.
