### ISSUE TITLE
How to Adjust SVG Size in a Styled Toggled Component in React

### ISSUE THREAD

**Issue by abdullahcicekli** [AlfieJones/theme-toggles#32]
Hi,
I have a component that I use like this: <Classic toggled={isToggled} toggle={() => handleThemeToggle()} className="w-100"/>. When I apply styles to it, the SVGs do not enlarge. Which prop should I use if I want to make them larger, like on your website? Or is this feature available?

**Comment by AlfieJones** [comment]
They use the font size by default so you can use `text-xl`. I'll probably look to change this in the next version.

Shows how we set the height & width internally https://github.com/AlfieJones/theme-toggles/blob/v4/packages/react/src/toggles/Classic.tsx#L57C1-L58C25. In v5 I'm planning on allowing users to override this.

If you'd like to use the tailwind h-* and w-* I'd suggest using the svg directly

**Comment by abdullahcicekli** [comment]
Thank you. This worked for me 😊
